name: 📦 Build iStoreOS 24.10.x x86_64

on:
  workflow_dispatch:
    inputs:
      include_docker:
        description: |
          是否编译 Docker 插件
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set executable permissions
      run: | 
        chmod +x x86/build24.sh
        chmod +x shell/*.sh
        
        
    - name: ⚙️ 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zstd curl unzip tree
      
    - name: ⏬ 下载 ImageBuilder
      run: |
        curl -L -o imagebuilder.tar.zst https://fw0.koolcenter.com/iStoreOS/ib/x86_64/istoreos-imagebuilder-x86-64.Linux-x86_64.tar.zst
        tar --use-compress-program=unzstd -xvf imagebuilder.tar.zst
        mv istoreos-imagebuilder-* imagebuilder
        
    
    - name: ⏬ 复制必备文件
      run: |
        cp x86/build24.sh imagebuilder/
        cp x86/Makefile imagebuilder/
        cp x86/repositories.conf imagebuilder/
        cp shell/prepare-packages.sh imagebuilder/
        cp shell/custom-packages.sh imagebuilder/
        mkdir -p imagebuilder/files/etc/uci-defaults
        cp files/etc/uci-defaults/99-custom.sh imagebuilder/files/etc/uci-defaults/
        echo "打印action目录结构"
        tree -L 1

    - name: 🧱 构建iStoreOS固件
      working-directory: ./imagebuilder
      run: |
        echo "打印imagebuilder目录结构"
        tree -L 1
        echo "打印repositories"
        cat repositories.conf
        echo "打印Makefile"
        cat Makefile |grep here
        bash ./build24.sh

    - name: 📦 打印产出固件
      run: |
        echo "打印bin目录"
        ls -lah imagebuilder/bin/targets/x86/64/

    - name: 🚀 上传到 Release
      uses: softprops/action-gh-release@v2.2.1
      with:
        tag_name: iStoreOS-24.10.6-x86-efi
        files: |
          imagebuilder/bin/targets/x86/64/*squashfs-combined-efi.img.gz
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

